name: polling

on:
  schedule:
    # 平日（月〜金）の JST 18:00〜翌08:00（UTC 09:00〜23:55）
    - cron: '*/5 9-23 * * 1-5'  # 月〜金 UTC 09:00〜23:55 = JST 18:00〜翌08:55

    # 土日終日（UTCで0〜23時を5分ごと）→ JSTで土日終日
    - cron: '*/5 * * * 6,0'     # 土(6), 日(0)
  workflow_dispatch:            # 手動実行用（任意）

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        env:
          URL1: ${{ secrets.URL1 }}
          URL2: ${{ secrets.URL2 }}
        run: python main.py
